allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
ignoredBuiltDependencies:
  - unrs-resolver
minimumReleaseAgeExclude:
  - '@better-auth/core@1.6.13'
  - '@better-auth/drizzle-adapter@1.6.13'
  - '@better-auth/kysely-adapter@1.6.13'
  - '@better-auth/memory-adapter@1.6.13'
  - '@better-auth/mongo-adapter@1.6.13'
  - '@better-auth/prisma-adapter@1.6.13'
  - '@better-auth/telemetry@1.6.13'
  - better-auth@1.6.13
  - tsx@4.22.4
